spring.application.name=core-logistics

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.liquibase-schema=public

spring.datasource.url=jdbc:postgresql://${DB_HOST:pg-logistics}:${DB_PORT:5432}/${POSTGRES_DB:logistics}?targetServerType=master&prepareThreshold=0
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.topic.hub.capacity.alerts.name=logistics.hub.capacity.alerts


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

app.outbox.batch.size=50
app.outbox.delay=1000
